import {StyleSheet} from 'react-native';
import colors from '../../utils/color';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  wrapperStepper: {
    height: 55,
    width: '100%',
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 0.5,
    borderBottomColor: 'grey',
  },
  padding: {padding: 16},
  lineHorizontal: {
    height: 0.5,
    width: '100%',
    backgroundColor: 'lightgrey',
    marginTop: 10,
  },
  paddingHorizontal: {paddingHorizontal: 16},
  fill: {flex: 1},
  contentDetailPesanan: {flexDirection: 'row', flex: 1},
  circleBg: {
    height: 18,
    width: 18,
    borderRadius: 18 / 2,
    backgroundColor: colors.blue,
    marginHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  txtTittleStepper: {
    color: colors.black,
    fontSize: 13,
    fontWeight: '600',
  },
  txtNumber: {color: colors.white, fontSize: 10},
  line: {
    width: 20,
    height: 1,
    backgroundColor: colors.blue,
    opacity: 0.35,
  },
  height: {height: 10},
  txtCard: {
    fontSize: 12,
    color: colors.black,
  },
  txtCardTitle: {
    fontSize: 12,
    color: colors.black,
  },
  wrapperCard: {
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'lightgrey',
    padding: 8,
    flexDirection: 'row',
  },
  imgCard: {
    height: 60,
    width: 60,
    marginEnd: 10,
    borderRadius: 10,
  },
  wrapperColumnCard: {justifyContent: 'center', flex: 1},
  contentCheckIn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  leftContent: {flex: 1, alignItems: 'flex-start'},
  rightContent: {flex: 1, alignItems: 'flex-end'},
  txtCheck: {
    fontSize: 14,
    color: colors.black,
    fontWeight: 'bold',
  },
  txtDate: {
    fontSize: 12,
    color: colors.grey,
    fontWeight: '600',
  },
  txtRefund: {
    fontSize: 13,
    color: colors.orange,
    fontWeight: 'bold',
    width: '60%',
    textAlign: 'justify',
  },
  txtUnderline: {
    fontWeight: 'bold',
    color: colors.blue,
    textDecorationLine: 'underline',
    textAlignVertical: 'center',
  },
  wrapperRadio: {
    alignItems: 'flex-start',
    paddingStart: 5,
    marginTop: -5,
    justifyContent: 'center',
  },
  labelRadio: {
    color: colors.black,
    fontSize: 13,
  },
  wrapperItemTamu: {
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'lightgrey',
    marginVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  imgItemTamu: {marginEnd: 10},
  cardEmpty: {
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'lightgrey',
    borderRadius: 5,
  },
  txtEmpty: {fontWeight: 'bold', fontSize: 12, color: 'grey'},
});
